apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: fluentd

commonLabels:
    app.kubernetes.io/name: fluentd
    app.kubernetes.io/managed-by:  Kustomize

resources:
- fluentd-bundle.yaml
