---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

commonLabels:
  app.kubernetes.io/name: mysql
  app.kubernetes.io/managed-by: Kustomize

resources:
  - mysql-bundle.yaml
  - sealed-secrets.yaml

configurations:
  - sealed-secret-config.yaml

# generatorOptions:
#   annotations:
#     sealedsecrets.bitnami.com/managed: "true"
#     sealedsecrets.bitnami.com/namespace-wide: "true"

# secretGenerator:
#   - name: mysql
#     type: Opaque

configMapGenerator:
  - name: mysql
    files:
      - my.cnf=cfg/my.cnf
  - name: bootstrap
    files:
      - bootstrap.sh=cfg/bootstrap.sh
