---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: database

commonLabels:
  app.kubernetes.io/name: mysql
  app.kubernetes.io/managed-by: Kustomize

resources:
  - mysql-bundle.yaml

configMapGenerator:
  - name: mysql
    files:
      - my.cnf=cfg/my.cnf
  - name: bootstrap
    files:
      - bootstrap.sh=cfg/bootstrap.sh
