apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: elk

commonLabels:
    app.kubernetes.io/name: elastic-search
    app.kubernetes.io/managed-by:  Kustomize

resources:
- es-bundle.yaml
