---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
spec:
  template:
    spec:
      containers:
        - name: wordpress
          env:
            - name: WORDPRESS_DATABASE_NAME
              value: "wp1"
            - name: WORDPRESS_DATABASE_USER
              value: "wp1"
            - name: WORDPRESS_EMAIL
              value: "wp1@example.com"
            - name: WORDPRESS_FIRST_NAME
              value: "wp1"
            - name: WORDPRESS_LAST_NAME
              value: "wp1"
            - name: WORDPRESS_BLOG_NAME
              value: "Client-a Blog!"
