---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: client-a

resources:
  - ../../base
  - secrets.yaml

images:
  - name: docker.io/bitnami/wordpress
    newTag: 5.9.3-debian-11-r10

patchesStrategicMerge:
  - deploy.env.patch.yaml
  - ingress.patch.yaml
