---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: client-a

resources:
  - ../../base

images:
  - name: docker.io/bitnami/wordpress
    newTag: 5.9.3-debian-11-r10

patchesStrategicMerge:
  - deploy.env.patch.yaml
  - ingress.patch.yaml
 # - secret.yaml

generatorOptions:
  disableNameSuffixHash: false

secretGenerator:
  - name: wordpress
    behavior: merge
    env: .env-wp
  - name: wordpress-externaldb
    behavior: merge
    env: .env-db
