apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wordpress

commonLabels:
    app.kubernetes.io/name: wordpress
    app.kubernetes.io/managed-by:  Kustomize

resources:
- wp-bundle.yaml
